In [2]:
import pandas as pd
from pandas import json_normalize

import requests 
import json
import os
from dotenv import load_dotenv 

import time

In [3]:
load_dotenv()

True

In [4]:
key= os.getenv("token")

In [5]:
url= f"https://applications.icao.int/dataservices/api/incident?api_key={key}&StateOfOccurrence=&format=&StateOfOperator=&StateOfRegistry=&Year=2020"

In [6]:
res = requests.get(url)

In [41]:
plane_crash= res.json()

In [42]:
df_plane= pd.DataFrame(json_normalize(plane_crash))

In [43]:
df_plane.dropna(how= 'all',inplace= True)

In [44]:
df_plane.columns

Index(['Date', 'StateOfOccurrence', 'Location', 'Model', 'Registration',
       'Operator', 'StateOfRegistry', 'FlightPhase', 'Class', 'Fatalities',
       'Over2250', 'Over5700', 'ScheduledCommercial', 'InjuryLevel',
       'TypeDesignator', 'Helicopter', 'Airplane', 'Engines', 'EngineType',
       'Official', 'Risk', 'OccCats', 'Year', 'StateOfOperator'],
      dtype='object')

In [46]:
df_plane.drop(columns= ["StateOfOccurrence", "Registration","FlightPhase","Helicopter","Airplane", "Engines","EngineType","StateOfOperator","OccCats","Official","Over2250","Over5700","TypeDesignator","ScheduledCommercial","Risk" ], inplace= True, axis =1)

In [47]:
df_plane.Class

,Date,Location,Model,Operator,StateOfRegistry,Class,Fatalities,InjuryLevel,Year
0,2020-01-01T00:00:00.000Z,Beijing,A333,Malaysia,MYS,Incident,,,2020
1,2020-01-01T00:00:00.000Z,Zurich,A343,Edelweiss,CHE,Incident,,,2020
2,2020-01-01T00:00:00.000Z,Lyon,CRJX,Hop!,FRA,Incident,,,2020
3,2020-01-01T00:00:00.000Z,Amsterdam,B738,KLM,NLD,Incident,,,2020
4,2020-01-01T00:00:00.000Z,Frankfurt,A359,Thai,THA,Incident,,,2020
...,...,...,...,...,...,...,...,...,...
848,2020-12-30T00:00:00.000Z,Rio de Janeiro,B738,Gol,BRA,Incident,,,2020
849,2020-12-30T00:00:00.000Z,Perpignan,B772,France,FRA,Incident,,,2020
850,2020-12-31T00:00:00.000Z,Irkutsk,B773,KLM,NLD,Incident,,,2020
851,2020-12-31T00:00:00.000Z,N'Djamena,A332,France,FRA,Incident,,,2020
852,2020-12-31T00:00:00.000Z,Bogota,A319,Avianca,USA,Incident,,,2020

In [31]:
df_trump=pd.read_csv("data/trump_insult.csv")

In [39]:
df_trump

,Unnamed: 0,date,target,insult,tweet
0,1,2014-10-09,thomas-frieden,fool,"Can you believe this fool, Dr. Thomas Frieden ..."
1,2,2014-10-09,thomas-frieden,DOPE,"Can you believe this fool, Dr. Thomas Frieden ..."
2,3,2015-06-16,politicians,all talk and no action,Big time in U.S. today - MAKE AMERICA GREAT AG...
3,4,2015-06-24,ben-cardin,It's politicians like Cardin that have destroy...,Politician @SenatorCardin didn't like that I s...
4,5,2015-06-24,neil-young,total hypocrite,"For the nonbeliever, here is a photo of @Neily..."
...,...,...,...,...,...
10355,10356,2021-01-06,2020-election,Many States want to decertify the mistake they...,If Vice President @Mike_Pence comes through fo...
10356,10357,2021-01-06,2020-election,"based on irregularities and fraud, plus corrup...","States want to correct their votes, which they..."
10357,10358,2021-01-06,2020-election,Our Election Process is worse than that of thi...,"They just happened to find 50,000 ballots late..."
10358,10359,2021-01-06,2020-election,a FRAUD,The States want to redo their votes. They foun...
10359,10360,2021-01-06,chuck-todd,"Sleepy Eyes, Sad to watch!",Sleepy Eyes Chuck Todd is so happy with the fa...